{
  "downurl": "https://i7.meixincdn.com/v1/img/T1nYdWByDv1RCvBVdK.png",
  "ref":"http://pan-yz.chaoxing.com/?s=",
  "openurl":"https://i7.meixincdn.com/v1/img/T1nYdWByDv1RCvBVdK.png",
  "stopurl":"1",
  "starturl":"1",
  "name":"电视剧一键获取入库 v3.8.9.exe",
  "ua":"Yunziliao.",
  "load":"-2",
  "version": "3.8",
  "smallver":"9",
  "release":"[3.8.9]",
  "exit":"stop",
  "md5":"9096cd60b2f3c4fca70706f97090e8fc",
  "authority":"www.596ys.com,www.juputi.comwww.zhaozhaozhu.com,www.hukandy.com,173dy.com,www.173dy.com,www.guojuren.com,www.qpgds.com,www.juji100.com,www.726kan.com,www.xiaoli123.com,www.qpgpd.com,www.kanjuren.com,v.diekaw.com,www.diekaw.com,www.haineiyy.com,v.haineiyy.com,www.diezhanmi.cc,www.diezhanme.com,v.diezhanmi.cc,v.diezhanmi.cc,www.918pd.cc,www.gangjume.com,www.diekan.cc,www.jujuyo.com,www.idiezhan.com,www.234pd.com,www.726ys.com,www.dvd160.com,www.wasds.com,www.yingjuba.cc,www.52lgsc.com,www.jjdvd.com,www.hmitv.com,www.hmitv.com,www.58vod.com,www.yjvod.com,www.dianrantv.com,www.jude100.com,www.7xvod.com,www.xbldy.com,www.haiantv.com,www.voddd.com,www.918sjw.com,www.lzlxyy.com,www.wulidy.com,www.diecuomi.com,www.diejumi.com,www.waitatv.com,www.dccyy.com,www.xykan.com,www.yddddd.com,www.wspyy.com,www.diezhan.vip,www.huashayy.com,www.acyyys.com,www.guokayy.com,www.sbbyy.com,www.libaitv.com,www.libaitv.cc,www.858vod.com,www.bueryy.com,www.kubmv.com,www.ku5tv.com,www.dieww.com,www.soyuntv.com,www.hemyy.com,www.idiemi.com,www.dieka.cc,www.tvbobo.com,www.qcmvs.com,www.woniucd.com,www.cimaomao.com,dieys.com,www.dieys.com,diezhanm.com,www.yemaoyy.com,www.zjjhfc.com,www.gcgzj.com,www.xxldy.com,www.bjbja.com,www.gygysp.com,www.gudacc.com,www.sigetv.com,www.hzwcms.com,app.azmzm.com,app.hemavod.com,v.hemavod.com,www.hemavod.com,app.haomitv.com,app.mgtvyun.com,m.jq100.cc,seacms.haomitv.com,www.918sjw.com,www.haiantv.cc,www.wulidy.cc,gydytt.com,zumaiso.com,rxdvd.com,tkyy3.com,tjhtlw.com,localhost,127.0.0.1,120.48.24.1",
  "limit":"guojuren,7xvod,idiemi",
  "log": "更新内容：\r\n1.新增2个资源站\r\nPS：2021/08/21 13:30:00",
  "err":"本软件已永久停用！",
  "token":"3.14159"
}